### ISSUE TITLE
what ??

### ISSUE THREAD

**Issue by wuxinvip** [10Dimensional/hugo-algolia#13]
![91p_7k _q 339k e pp cx](https://user-images.githubusercontent.com/20430852/40618837-545ff530-62c5-11e8-9be7-bb1a05c52cdd.png)

![yk9ga 2 d 0uj o f01](https://user-images.githubusercontent.com/20430852/40618841-58c9306e-62c5-11e8-88f9-2a54de2f84e1.png)

![31_ hh 9hk1tyduffmf7f](https://user-images.githubusercontent.com/20430852/40618846-5c4db930-62c5-11e8-8348-a92d8ce47a5f.png)

all i tried  . . . still there.

**Comment by rzkmak** [comment]
got the same problem today, after reading the code, I see that the YAML parser need to be a valid YAML block starting with ---

example: 
```
---
baseURL: ""
algolia:
 index: "algolia-indexes"
 key: "some-key"
 appID: "app-id"
```
