### ISSUE TITLE
algolia.json output not contain Chinese data content

### ISSUE THREAD

**Issue by Honghe** [10Dimensional/hugo-algolia#14]
## Environment
* Ubuntu 16.04
* hugo-algolia 1.2.7

## config.yaml
```
---
baseurl: "/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "Blog"
theme: "concise"
metaDataFormat: "yaml"
algolia:
  index: "honghe-blog"
  appID: "WC46GFS5NE"
---
```

## source file hugo_note.md
```
---
title: "Hugo note"
date: 2018-06-03T19:12:41+08:00
typora-copy-images-to: images
layout: "bundle-resource-meta"

math: true
tags: []
categories: []
---

# Extension

## Search

algolia

测试中文统计测试中文统计测试中文统计测试中文统计测试中文统计测试中文统计测试中文统计测试中文统计测试中文统计测试中文统计测试中文统计测试中文统计测试中文统计测试中文统计测试中文统计测试中文统计

# Q&A

##  GitHub Flavored Markdown

https://github.com/gohugoio/hugo/issues/158
```

## algolia.json output
```
    {
        "title": "Hugo note",
        "uri": "posts/gohugo/hugo_note",
        "content": "Extension Search algolia                                                                                                  Q A GitHub Flavored Markdown https   github com gohugoio hugo issues 158",
        "objectID": "posts/gohugo/hugo_note",
        "date": "2018-06-03T11:12:41.000Z",
        "typora-copy-images-to": "images",
        "layout": "bundle-resource-meta",
        "math": true,
        "tags": [],
        "categories": []
    },
```
